version: "3.6"

services:
  vijay-portfolio:
    build:
      context: .
      dockerfile: vijay-portfolio/Dockerfile
    restart: always
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=vijayportfolio.com,www.vijayportfolio.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=vijayportfolio.com,www.vijayportfolio.com
      - LETSENCRYPT_EMAIL=your-email@example.com  # Update with your email

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - vijay-portfolio
